name: build cli for all platforms

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
  build-all-for-all:
    runs-on: ubuntu-latest
    needs:
      - make-release
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        # exclude:
        #   - goarch: arm64
        #     goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          md5sum: false
          sha256sum: false
          compress_assets: false
